[target.bpfel-unknown-none]
rustflags = ["-C", "debuginfo=2", "-C", "link-arg=--btf"]

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
rustflags = [
    # Compressing debug information can yield hundreds of megabytes of savings.
    # The Rust toolchain does not currently perform dead code elimination on
    # debug info.
    #
    # See: https://github.com/rust-lang/rust/issues/56068
    # See: https://reviews.llvm.org/D74169#1990180
    "-C", "link-arg=-Wl,--compress-debug-sections=zlib",

    # I'm not using a 386 anymore
    "-C", "target-cpu=x86-64-v3",
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    # Compressing debug information can yield hundreds of megabytes of savings.
    # The Rust toolchain does not currently perform dead code elimination on
    # debug info.
    #
    # See: https://github.com/rust-lang/rust/issues/56068
    # See: https://reviews.llvm.org/D74169#1990180
    "-C", "link-arg=-Wl,--compress-debug-sections=zlib",

    # I'm not using a 386 anymore
    "-C", "target-cpu=x86-64-v3",
]
